### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by mostafa1996** [davidtrpcevski/Advanced-LineageOS-Releases#4] opened 2019-12-07 03:52 UTC
can u add features which can be found in pixel experience plus u made last month 

its minimum but very helpful 

and what happened to ur kernel ? 

can u also make telegram channel instead of xda ?

**Comment by mostafa1996** [comment] 2019-12-07 04:21
bug report 

Facebook keeps fc with no message

**Comment by davidtrpchevski** [comment] 2019-12-07 10:56
1. I don't do features requests. What I include is what I use.

2. There is no my kernel since it comes prebuilt with these builds. Kernel sources can be found [here](https://github.com/davidtrpcevski/kernel_xiaomi_msm8953)

3. I rarely use XDA now until the forum improves. I do have telegram account, but it's for personal purposes.

4. I use Facebook on regular basis, so I can't detect anything. Please read the FAQ again, if I don't get a log I will close this issue.

**Comment by mostafa1996** [comment] 2019-12-07 11:20
i hope this helps 
i even tried to change the kernel but it didn't help

[logs-2019-12-07-13-19-02.zip](https://github.com/davidtrpcevski/LineageOS-Releases/files/3935003/logs-2019-12-07-13-19-02.zip)

**Comment by davidtrpchevski** [comment] 2019-12-07 11:31
> i hope this helps
> i even tried to change the kernel but it didn't help
> 
> [logs-2019-12-07-13-19-02.zip](https://github.com/davidtrpcevski/LineageOS-Releases/files/3935003/logs-2019-12-07-13-19-02.zip)

Can't help much here since it is related to the Facebook app from the looks of it. Try reinstalling it or clean flash.

**Comment by mostafa1996** [comment] 2019-12-07 11:37
it looks like the problem happens in instegram too 

i notice it usually happens when i scroll fast

**Comment by mostafa1996** [comment] 2019-12-07 12:35
> > i hope this helps
> > i even tried to change the kernel but it didn't help
> > [logs-2019-12-07-13-19-02.zip](https://github.com/davidtrpcevski/LineageOS-Releases/files/3935003/logs-2019-12-07-13-19-02.zip)
> 
> Can't help much here since it is related to the Facebook app from the looks of it. Try reinstalling it or clean flash.

i did already clean flash and reinstalling the app but it didn't help 
also the problem happens in instegram and LinkedIn too

**Comment by davidtrpchevski** [comment] 2019-12-07 15:41
Issue has been confirmed and it is caused by Google's latest security patch. Me and the LineageOS team have confirmed and a fix has been pushed to LineageOS gerrit. The next release will have the patch implemented. Sorry for inconvenience.

**Comment by mostafa1996** [comment] 2019-12-07 20:53
its ok bro np

**Comment by davidtrpchevski** [comment] 2019-12-08 09:27
Please confirm if the issue is fixed in the new release. If it is, please feel free to close this issue.

**Comment by davidtrpchevski** [comment] 2019-12-11 12:28
Extensively tested above apps, no crashes were found by my side. Considering this as fixed.

**Closed as completed by davidtrpchevski** 2019-12-11 12:28 UTC
